### PR TITLE
Russian translation of "Handy guide"

### PR DESCRIPTION
**Pull request by saviorand**
Thanks for the repo!

### CODE REVIEW

**Comment by nayafia** [comment]
Hi @saviorand, thanks for the translation!

It looks like this PR replaces the *entire* English readme with Russian. Instead, you just need to add a link to your translation.

You can fix it in this PR, or it might be easier to just close this PR and open a new one, where you simply add your link (`https://github.com/saviorand/lemonade-stand`) as the Russian translation in this part of README.md, following the same format as the other translations:

```
TRANSLATIONS: [Traditional Chinese(繁體中文)](https://github.com/jserv/lemonade-stand) // [Simplified Chinese(簡體中文)](https://github.com/wizicer/FinancialSupportForOpenSource) // [Italian(italiano)](https://github.com/dakk/lemonade-stand) // [Japanese(日本語)](https://github.com/fumikito/lemonade-stand) // [Spanish(español)](https://github.com/fredbesan/lemonade-stand)
```

You can use the diff here as a guide: https://github.com/nayafia/lemonade-stand/pull/101/files

**Comment by nayafia** [comment]
Closed by https://github.com/nayafia/lemonade-stand/pull/105

**Comment by oshliaer** [comment]
@saviorand , у вас есть репозиторий с переводом?

**Comment by oshliaer** [comment]
https://github.com/saviorand/lemonade-stand_ru

**Pull request closed without merging**
