### PR TITLE
Added Managed / Hosted Services

### PR DESCRIPTION
**Pull request by aterrel**
I felt this model is different enough it deserves it's own section.

### CODE REVIEW

**Comment by ktosiek** [comment]
I love the idea of separate section, Sentry being listed as open core brought me to the issues page :-)

Also, is Gitlab hosting their free code? They are a bit of an outlier, as they are publishing some code (gitlab EE) that you can't use without a paid licence. Do we still call that open source here? Or would the EE part be considered proprietary (like in open core)?

**Comment by aterrel** [comment]
I'm not sure if Gitlab.com is Gitlab CE or GitlabEE. I would say the
company is doing both the Managed Service and Core / Premium Closed model.

**Comment by ktosiek** [comment]
Just checked: https://about.gitlab.com/gitlab-com/ says it "Runs GitLab Enterprise Edition with issue tracking, wikis, and CI.". So it's an Open Core Managed Service :-)

**Comment by nayafia** [comment]
beautiful. thank you for your help!

**Pull request merged**
